---
title: "analysis.do"
---

The `analysis.do` do-file generates the bar graphs that constitute the main analysis you do for this assignment, using the data in your final `analysis.dta` file. Write commands in `analysis.do` that accomplish the following:

-   Open the data file `analysis.dta` (which, after you have written and run `processing.do`, should be saved in your `/Analysis-Data` folder).

-   Generate a bar graph, with two bars, where:

    -   one bar represents students living in alcohol-free housing
    -   one bar represents students who do not live in alcohol-free housing
    -   the height of each bar is equal to the proportion of students (in the group the bar represents) who drank enough to get drunk three or more times in the last thirty days

Save this graph in the `/For-Report` subfolder of the `/Graphs` folder, with the name `Figure1.gph`. (Use a relative directory path to specify the location of the For-Report sub-folder.)

-   Generate a bar graph, with two bars, where:
    -   one bar represents students who live in alcohol-free housing because they requested it
    -   one bar represents students who live alcohol free housing because they were assigned to it the height of each bar is equal to the proportion of students (in the group the bar represents) who drank enough to get drunk three or more times in the last thirty days

Save this graph in the `/For-Report` subfolder of the `/Graphs` folder, with the name `Figure2.gph`.

-   Generate a bar graph, with four bars, where:
    -   each bar represents students in one of the four categories defined by the variable housing
    -   the height of each bar is equal to the proportion of students (in the group the bar represents) who drank enough to get drunk three or more times in the last thirty days
    -   Save this graph in the `/For-Report` subfolder of the `/Graphs` folder, with the name `Figure3.gph`.
-   Generate two side-by-side bar graphs, each consisting of two bars, where:
    -   one of the bar graphs represents only students who had five or more drinks in a row on three or more occasions during their last year of high school
    -   one of the bar graphs represents only students who had five or more drinks in a row on fewer than three occasions during their last year of high school

**and in each of these graphs,**

-   one bar represents students who live in alcohol-free housing
-   one bar represents students who do not live in alcohol-free housing
-   the height of each bar is equal to the proportion of students (in the group the bar represents) who drank enough to get drunk three or more times in the last thirty days

Save this graph in the `/For-Report` subfolder of the `/Graphs` folder, with the name `Figure4.gph`.

-   Generate two side-by side bar graphs, each consisting of two bars, where:
    -   one of the bar graphs represents only students who had five or more drinks in a row on
    -   three or more occasions during their last year of high school one of the bar graphs represents only students who had five or more drinks in a row on fewer than three occasions during their last year of high school

**and in each of these graphs,**

-   one bar represents students who live in alcohol-free housing because they requested it
-   one bar represents students who live alcohol free housing because they were assigned to it
-   the height of each bar is equal to the proportion of students (in the group the bar represents) who drank enough to get drunk three or more times in the last thirty days Save this graph in the `/For-Report` subfolder of the `/Graphs` folder, with the name `Figure5.gph`.

```{=html}
<!-- -->
```
-   Generate two side-by side bar graphs, each consisting of four bars, where:
    -   one of the bar graphs represents only students who had five or more drinks in a row on three or more occasions during their last year of high school
    -   one of the bar graphs represents only students who had five or more drinks in a row on fewer than three occasions during their last year of high school

**and in each of these graphs,**

-   each bar represents students in one of the four categories defined by the variable housing
-   the height of each bar is equal to the proportion of students (in the group the bar represents) who drank enough to get drunk three or more times in the last thirty days

Save this graph in the `/For-Report` subfolder of the `/Graphs` folder, with the name `Figure6.gph`.

::: {.callout-note appearance="simple"}
Write comments indicating which commands produce which graphs: For example, before the command that generates Figure 4, write a comment like “The following command generates Figure 4.”
:::

Remember to save `analysis.do` in your `/Command-Files` folder.

### Cleaning up your do-files

Writing the do-files that accomplish the tasks outlined above will be a large part of the work you do for this exercise.  For most of the tasks, your first attempt at writing a command or commands won't work—you will get error messages, or something will be obviously incorrect, and you will need to try again, maybe several times, before you figure out syntax that works.  

When you have finally gotten everything in a do-file to run successfully, you may well have accumulated a lot of extra stuff that is no longer relevant: commands that were first tries, false starts, or exploration to figure out how things work.

At the end of the exercise, when you are preparing the final electronic documentation to submit with your printed report, you should clean up your do-files:  remove any first tries, false starts and exploration that turned out to be mistakes or that do not serve any purpose.  The only commands left in the do-files you submit with your documentation should be ones that do something necessary to accomplish the required tasks.

And remember to include comments throughout your do-files explaining the purpose of the commands at each step of the data processing and analysis.

:::{.callout-tip collapse="true"}
Your do-files of course need to run properly and execute the steps of data processing and analysis that reproduce your results.  But they should also be useful documents to a human reader who wants to learn about what you did for this project.  Keep that goal in mind as you do your final clean-up of the commands and insert comments.
:::