---
title: "Dataset and Codebook" 
---
Download and examine the dataset and codebook you will use for this exercise

Find and explore the website where the data for this exercise are stored.  The data used in this exercise come from a study titled Harvard School of Public Health College Alcohol Study, 2001.  This study is archived at the Inter-University Consortium for Political and Social Research (ICPSR); its ICPSR study number is 4291.   

Go to the [ICPSR website](https://www.icpsr.umich.edu) (www.icpsr.umich.edu), and search for this study.
When you have found the page for this study, read the information provided there

::: {.callout-tip collapse="true"}
Some of the information on the webpage for the dataset may have to do with technical matters you don’t understand or details that may not appear important, but that is OK.  Just read through the page and get out of it what you can.
:::

### Download the dataset and codebook
Before you can download the data, you need to create an account on the ICPSR website. Once you have done so, log in, go to the main page for the 2001 alcohol study, and click on the "Download" button.  You will get a menu of formats to choose from, including SAS, SPSS, Stata, and ASCII.  From this menu, **select Stata.**

The data file will be downloaded in a zipped folder.  When you unzip and look inside the folder, you will see that it contains several documents, as well as a subfolder called `/DS0001`  For this exercise, you will need to use only two of the files you downloaded, both of which will be stored in the `/DS0001` subfolder: 

> `04291-0001-Data.dta`  This file contains the data from the survey, stored in Stata's .dta format.  This file will be referred to as the "original data file" for this exercise.

> `04291-0001-Codebook.pdf`  This is the codebook for the 2001 alcohol survey.  It will be referred to as the "metadata" for the original data file.

You should save copies of both of these files in the folder hierarchy you created for this exercise.

Save the original data file in the `/Original-Data` folder.

Save the codebook in the `/Metadata` folder (which is inside your Original-Data folder).

### Examine the codebook and dataset

Examine the codebook and original data file to familiarize yourself with the information they contain.

In particular, by reading the codebook and using Stata to explore the contents of the data, answer the following questions:

- What is the recommended format for citations of this dataset (to use, for example, in a reference list or a list of data sources)?

- How many observations are there in the dataset?

- How many variables are there in the dataset?

- What is the unit of analysis for the dataset?  

- What population was the sample represented in this dataset taken from?

For this exercise, you will need to use six variables from alcohol study.  In the original data file, these variables have the names `A6, B8, B9, C13, G6,` and `G11`.

For each of these variables, answer the following questions:

- How is the variable defined, or what does it represent?

- What units is the variable measured in, or what is the coding scheme?

- Is it categorical or quantitative?  

- If it is quantitative, find the mean, standard deviation, the three quartiles, the minimum and the maximum.

- It if is categorical, how many categories are there, what do they represent, and what proportion of the observations fall in each category?

- For each categorical variable, decide whether the categories are ordered or unordered

Finally, suppose you wanted know what college or university each student in the sample attended.  Would you be able to find that out using the codebook and dataset you downloaded from ICPSR?  If so, how would you do so?  If not, do you have any idea why that information is not provided?

::: {.callout-tip collapse="true"}
You will not need to turn in written answers to these questions, and you will not need to turn in do-files that document this preliminary exploration of your data.  However, it is important to convince yourself that you understand all of the questions well.  If you are hazy on any of them, you are likely to encounter trouble as you work on the parts of the exercise that you do have to turn in.
:::


## General comments about organizing your work and writing do-files
### Folder structure and file locations.
Before you begin working on your do-files, make sure that you have created a folder hierarchy as described [here](https://connor1883.github.io/quarto-demo/alcohol-exercise/folders.html#create-a-set-of-folders-to-store-your-work-in), and that you have put the original data and the codebook in the folders specified [here](https://connor1883.github.io/quarto-demo/alcohol-exercise/dataset-and-codebook.html).  As you work on this exercise, you will be creating new files of various kinds, and storing them in designated locations in this hierarchy.

Whenever you are working with Stata, a copy of your complete folder hierarchy, with the most up-to-date versions of all your files stored in their designated locations, should be saved on the computer you are working on.  


