---
title: "Overview"
---

For this exercise you will write three do files:

### `processing.do`  

In most studies involving statistical data (including this exercise), the original data must be processed before they are ready to be analyzed.  For example, this processing may include correcting or removing errors in the original data, dropping variables or observations, generating new variables, and (when your original data are stored in more than one file) combining data files.

Data on which all the processing necessary to prepare them for analysis has been completed are referred to as "analysis data."  These are the data that will be used to generate the results that are presented in the final report on the study. 
The processing.do do-file you write for this exercise will contain commands that open up the original data file `04291-0001-Data.dta`, process the data as necessary to create your analysis data file, and then save the analysis data in a file named analysis.dta. 

### `data-appendix.do`  

The Data Appendix is a document that serves as a codebook or user's guide for your analysis data.  It contains variable definitions, coding and summary statistics (numeric and graphical) for all the variables in your analysis data.
The `data-appendix.do` do-file will contain commands that open up your analysis data file `analysis.dta`and then generate the summary statistics and other information that you will include in the Data Appendix.

### `results.do`

Figures, tables and other information presented in a report about a study that were generated by computations performed on statistical data are referred to as "results."

For this exercise, the results consist of six bar graphs. The `results.do` do-file will contain commands that open up `analysis.dta`, and then generate those graphs, saving each graph when it is created.