---
title: "Setting up the workspace"
---
## Create a set of folders to store your work in

Decide where you will keep your work.  Depending on your preferences and the technology you are using, you may store these folders locally (on the hard disk of a computer you will be using), on a storage server or course management system maintained by your institution, or on-line using a platform such as the [Open Science Framework](<https://www.osf.io>), [Dropbox](<https://www.dropbox.com>), or [Google Drive](<https://drive.google.com>)]. 

In any case, you should choose a place to store these folders that is secure and that you will be able to access easily while you work on this exercise.  

Wherever you store these folders, be sure that there is system in place to automatically back them up, or that you manually maintain an up-to-date set of back-up files at all times.

Create your folders.  An essential step toward ensuring that your data processing and analysis are easily reproducible is creating a folder hierarchy—a set of folders (and folders-within-folders) with a well-defined structure—in which you store your data, command files, and accompanying documents.  You should create this set of folders at the very beginning of your work—before you even obtain the data you will be using.

You will keep all your files in these folders while you work on this exercise, and when you have finished you will use them to store the electronic documentation that you submit with your printed report.

### Create the folder hierarchy for this exercise

Make a new folder with the name `Your-Name-Alcohol-Exercise`, and save it in the location you chose to save your work in.  This will be the main folder in which you store all of your work for this exercise.


Next create the following folders and sub-folders:
```
./Your-Name-Alcohol-Exercise/Original-Data
./Your-Name-Alcohol-Exercise/Command-Files
./Your-Name-Alcohol-Exercise/Graphs
```

In the `/Graphs` folder create the following sub-folders
```
/Graphs/For-Data-Appendix
/Graphs/For-Report
```

Finally, in the `/Original-Data` folder create the following subfolder
```
/Original-Data/Metadata
```

Your completed folder hierarchy should look like this
```
./Your-Name-Alcohol-Exercise
├── Original-Data
│   └── Metadata
├── Command-Files
└── Graphs
    ├── For-Data-Appendix
    └── For-Report
```

::: {.callout-tip collapse="true"}
Be sure to build this folder hierarchy before you proceed to the next steps of this exercise.  Having these folders set up in advance so that you have a place to put the various files you obtain or create while you work on this exercise will help things go smoothly.
:::
