---
title: "Writing the README"
---

The Read Me file is a document that provides information about the electronic files you have assembled to document your work for this exercise.  

It should consist of two main sections.

- The first section should provide an outline or map of all the files included in the replication documentation, and the folders and sub-folders in which they are stored.

- The second section should give step-by-step instructions explaining how to use your documentation to:
  1) Replicate all the data processing required to transform the original data into your analysis data file
  2) Generate all the computer output that you used in the Data Appendix
  3) Reproduce the six bar graphs you created.  

Those instructions should be written in plain English, and they should be clear and detailed enough that someone unfamiliar with this exercise would actually be able to follow them and replicate everything you did with your data.

## Formatting the Read Me file
The title "Read Me File for XXX" (where you substitute an informative title for XXX) should appear at the top of the document.  

The name(s) of the authors(s) of the exercise and the date it was turned in should also be shown at the top of the Read Me file.   The pages of the Read Me file should be numbered.

When the Read Me file is complete, you should save a copy of it in pdf format.  Give the file the name read-me.pdf.
A copy of read-me.pdf should be stored in the top level of your main project folder `./Your-Name-Alcohol-Exercise`.  
