---
title: "Anscombe’s Quartet: No Correlation Without Visualization!"
date: 2020-01-24
toc: true
---

# General description of the exercise

This exercise teaches some cautionary lessons about using correlation and regression to characterize the nature of the association between two variables.

The dataset used for this exercise is shown in the table below. It contains eight variables, with eleven observations each.

```         

      X1      Y1   X2     Y2   X3      Y3   X4     Y4  
_____________________________________________________
  1.  10    8.04   10   9.14   10    7.46    8   6.58 
  2.   8    6.95    8   8.14    8    6.77    8   5.76 
  3.  13    7.58   13   8.74   13   12.74    8   7.71 
  4.   9    8.81    9   8.77    9    7.11    8   8.84 
  5.  11    8.33   11   9.26   11    7.81    8   8.47 
  6.  14    9.96   14    8.1   14    8.84    8   7.04 
  7.   6    7.24    6   6.13    6    6.08    8   5.25 
  8.   4    4.26    4    3.1    4    5.39   19   12.5 
  9.  12   10.84   12   9.13   12    8.15    8   5.56 
 10.   7    4.82    7   7.26    7    6.42    8   7.91 
 11.   5    5.68    5   4.74    5    5.73    8   6.89 
```

The eight variables in the dataset will be treated as four pairs: (X1, Y1), (X2, Y2), (X3, Y3), (X4, Y4).

There are eleven observations for each variable. We will treat the values of the variables as quantitative (as opposed to categorical) data. But in fact, the values of these variables do not represent meaningful measurements of any kind. They were made up by a statistician named F. J. Anscombe, specifically for the purpose of illustrating the issues that you will explore in this exercise. The four pairs of variables in this dataset have come to be called "Anscombe's Quartet."

For this exercise, you will generate some univariate descriptive statistics to compare the distributions of the four X variables and the four Y variables, and calculate simple correlations and regressions to compare the associations between the X and Y variables in the four pairs. In the end you will produce a report in which you present your results and answer some questions that ask you to interpret them. Y ou will produce the report by writing an R Markdown file that contains R code chunks that execute the analyses you need to do, as well as Markdown code that generates the text of your report.

You will also construct an electronic "compendium" for this exercise, a folder in which you store the data, the R Markdown file you write, and some additional files that will be explained later in these instructions. The purpose of the compendium is to provide comprehensive documentation of your work that would make it easy for someone else to understand everything you did with the data, and to reproduce both the text and the computational results presented in your report.
