---
title: Overview
---

Your main task for this exercise is adding new text and code chunks to `YourNameReport.Rmd`, as described in the following instructions.
The basic approach is as follows:

- When a question asks you something that requires some computation, write a chunk of R code that executes the necessary computations and displays the results.  (But if for some reason you don't want the results generated by a certain code chunk to be included in the report, set the options for the chunk to hide the output).
- When you need to give a verbal response to a question, write your answer in text (with Markdown tags that will format the text correctly in the output file).

When you have finished writing all the necessary text and code chunks in `YourNameReport.Rmd`, you will knit it into the report you turn in for this exercise.  This report will present the results of the computations executed with R, as well as your answers to the questions enumerated below.

Begin typing the new text and code chunks at the bottom of `YourNameReport.Rmd`, below the header and two code chunks that appear at the top of the file.
Save `YourNameReport.Rmd` frequently while you are working on it to avoid losing your work.

Save `YourNameReport.Rmd` frequently while you are working on it to avoid losing your work.

:::{.callout-tip}
Whenever you write a code chunk, remember to insert comments explaining the purpose of each command or sequence of commands accomplishes.
:::


